version: '3'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - railsdata:/myapp
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  railsdata:
    driver: local
